# Generated by Django 4.2.7 on 2023-11-27 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
