# Generated by Django 4.2.7 on 2023-11-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightpass',
            name='hostel_checkin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nightpass',
            name='hostel_checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
