# Generated by Django 4.2.7 on 2023-12-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_nightpass_check_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightpass',
            name='check_in',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='nightpass',
            name='check_out',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='nightpass',
            name='date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='nightpass',
            name='valid',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
