# Generated by Django 4.2.7 on 2023-12-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_nightpass_check_in_alter_nightpass_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nightpass',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
