# Generated by Django 4.2 on 2023-11-18 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ThaparStaff',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('staff_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('registration_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('course', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=10)),
                ('parent_contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('picture', models.URLField(blank=True)),
                ('room_number', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('has_booked', models.BooleanField(default=False)),
                ('is_checked_in', models.BooleanField(default=True)),
                ('hostel_checkout_time', models.DateTimeField(blank=True, null=True)),
                ('hostel_checkin_time', models.DateTimeField(blank=True, null=True)),
                ('last_checkout_time', models.DateTimeField(blank=True, null=True)),
                ('violation_flags', models.IntegerField(default=0)),
                ('hostel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='hostel', to='users.hostel')),
            ],
        ),
        migrations.AddField(
            model_name='hostel',
            name='caretaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caretaker', to='users.thaparstaff'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='warden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.thaparstaff'),
        ),
    ]
