# Generated by Django 4.2.7 on 2023-12-13 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_student_gender_alter_nightpass_valid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nightpass',
            options={'verbose_name_plural': 'Night Passes'},
        ),
        migrations.AlterModelOptions(
            name='security',
            options={'verbose_name_plural': 'Security'},
        ),
    ]
