# Generated by Django 4.2.10 on 2024-03-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_student_registration_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='semester',
            new_name='year',
        ),
    ]
