# Generated by Django 4.2.10 on 2024-05-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_semester_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='defaulter_notification',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
