# Generated by Django 4.2.10 on 2024-05-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightpass',
            name='check_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nightpass',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nightpass',
            name='check_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nightpass',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nightpass',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='nightpass',
            name='hostel_checkin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nightpass',
            name='hostel_checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
