# Generated by Django 4.2 on 2023-10-31 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('picture', models.URLField(blank=True)),
                ('max_capacity', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booking', models.BooleanField(default=False)),
                ('is_display', models.BooleanField(default=False)),
                ('booking_complete', models.BooleanField(default=False)),
                ('slots_booked', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, choices=[('hostel', 'Hostel'), ('location', 'Location'), ('gate', 'Gate')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NightPass',
            fields=[
                ('pass_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('check_in', models.BooleanField(default=False)),
                ('check_out', models.BooleanField(default=False)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('campus_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nightpass.campusresource')),
            ],
        ),
    ]
