# Generated by Django 4.2.7 on 2023-11-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('picture', models.URLField(blank=True)),
                ('max_capacity', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booking', models.BooleanField(default=False)),
                ('is_display', models.BooleanField(default=False)),
                ('booking_complete', models.BooleanField(default=False)),
                ('slots_booked', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, choices=[('hostel', 'Hostel'), ('location', 'Location'), ('gate', 'Gate')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
