# Generated by Django 4.2.7 on 2023-12-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightpass', '0002_alter_campusresource_slots_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='backend_checkin_timer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='frontend_checkin_timer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
