# Generated by Django 4.2.7 on 2023-12-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_hostel_timers', models.BooleanField(default=False)),
                ('frontend_checkin_timer', models.IntegerField(blank=True, default=0, null=True)),
                ('backend_checkin_timer', models.IntegerField(blank=True, default=0, null=True)),
                ('last_entry_without_hostel_checkout', models.TimeField(blank=True, null=True)),
                ('valid_entry_without_hostel_checkout', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
