# Generated by Django 4.2.7 on 2023-12-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0002_settings_enable_gender_ratio_settings_female_ratio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'Settings'},
        ),
        migrations.AddField(
            model_name='settings',
            name='max_violation_count',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
