# Generated by Django 4.2.7 on 2024-02-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0003_alter_settings_options_settings_max_violation_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='enable_hostel_limits',
            field=models.BooleanField(default=False, help_text='Limit the number of students eligible for a particular hostel. Limit can be set from Hostel profile.'),
        ),
        migrations.AddField(
            model_name='settings',
            name='enable_yearwise_limits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='first_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='fourth_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='second_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='third_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='enable_hostel_timers',
            field=models.BooleanField(default=False, help_text='Enabling activates the time limits specified in the Hostel profile. The timers below, however, will not be operational.'),
        ),
    ]
