# Generated by Django 4.2.10 on 2024-03-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0005_settings_imagekit_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='announcement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
